use_frameworks!

target 'MaksabComponents_Example' do
  pod 'MaksabComponents', :path => '../'
  pod 'StylingBoilerPlate', :path => '/Users/mansoor/Documents/iOS/Maksab Space/StylingBoilerPlate'
  pod 'IQKeyboardManagerSwift'
  pod 'SideMenuController'
  pod 'Cosmos'
  pod 'MRProgress'
  
  target 'MaksabComponents_Tests' do
    inherit! :search_paths

    
  end
end
