use_frameworks!

target 'MaksabComponents_Example' do
  pod 'MaksabComponents', :path => '../'
#  pod 'StylingBoilerPlate', '0.1.20'
  pod 'IQKeyboardManagerSwift'
  pod 'SideMenuController'
  pod 'Cosmos'
  pod 'MRProgress'
  
  target 'MaksabComponents_Tests' do
    inherit! :search_paths

    
  end
end
