use_frameworks!

target 'MaksabComponents_Example' do
  pod 'MaksabComponents', :path => '../'
  pod 'StylingBoilerPlate'

  target 'MaksabComponents_Tests' do
    inherit! :search_paths

    
  end
end
